name: Build and Push API Docker Image

on:
  push:
    branches:
      - "main"

jobs:
  build-push-api:
    runs-on: ubuntu-latest
    if: needs.check-api-files-changed.outputs.files_changed == 'True'
    steps:
      # Only run if changed
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
      # Build and push api code
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: steps.changed-files-specific.outputs.any_changed == 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: steps.changed-files-specific.outputs.any_changed == 'true'
      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_CLIENT_ID }}
          password: ${{ secrets.ACR_CLIENT_SECRET }}
      - name: Build and push
        uses: docker/build-push-action@v3
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        with:
          context: "{{defaultContext}}:api"
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/assembly:latest
