name: Build and Push API Docker Image

on:
  push:
    branches:
      - "main"

jobs:
  build-push-api:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_CLIENT_ID }}
          password: ${{ secrets.ACR_CLIENT_SECRET }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:api"
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/assembly:latest
