name: Build and Push API Docker Image

on:
  push:
    branches:
      - "main"

jobs:
  check-api-files-changed:
    runs-on: ubuntu-latest
    # Declare outputs for next jobs
    outputs:
      files_changed: ${{ steps.check_file_changed.outputs.files_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2
      - shell: pwsh
        id: check_file_changed
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD

          # Check if a file under api/ or with the .md extension has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object { $_ -match '^api/' -or $_ -match '.md$' }
          $HasDiff = $SourceDiff.Length -gt 0

          # Set the output named "files_changed"
          Write-Host "files_changed::$HasDiff" >> $GITHUB_OUTPUT
  build-push-api:
    runs-on: ubuntu-latest
    needs: [check-api-files-changed]
    if: needs.check-api-files-changed.outputs.files_changed == 'True'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_CLIENT_ID }}
          password: ${{ secrets.ACR_CLIENT_SECRET }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:api"
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/assembly:latest
